version: '3.3'

services:

  rectify_app:
    image: tomcat:8.0-jre8
    volumes:
     - ./target/rectify-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/rectify.war
    ports:
      - "8080:8080"
    depends_on:
      - "rectify_db"
      
  rectify_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: rectify
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./rectify.sql:/docker-entrypoint-initdb.d/init.sql
    ports: 
      - "3306:3306"

  wordpress_db:
    image: mysql:5.7
    volumes:
        - db_data:/var/lib/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: mysql
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
    ports: 
      - "3307:3306"
      
  wordpress_app:
    depends_on:
        - wordpress_db
    image: wordpress:latest
    ports:
        - "8081:80"
    restart: always
    environment:
        WORDPRESS_DB_HOST: wordpress_db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress

volumes:
    db_data: