package pt.inesc.rectify.hibernate;
// Generated Dec 3, 2016 4:22:13 PM by Hibernate Tools 5.2.0.Beta1

/**
 * KbDbOpParts generated by hbm2java
 */
public class KbDbOpParts implements java.io.Serializable {

	private Integer id;
	private KbDbOp kbDbOp;
	private String type;
	private String partKey;
	private String value;

	public KbDbOpParts() {
	}

	public KbDbOpParts(KbDbOp kbDbOp) {
		this.kbDbOp = kbDbOp;
	}

	public KbDbOpParts(KbDbOp kbDbOp, String type, String partKey, String value) {
		this.kbDbOp = kbDbOp;
		this.type = type;
		this.partKey = partKey;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public KbDbOp getKbDbOp() {
		return this.kbDbOp;
	}

	public void setKbDbOp(KbDbOp kbDbOp) {
		this.kbDbOp = kbDbOp;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getPartKey() {
		return this.partKey;
	}

	public void setPartKey(String partKey) {
		this.partKey = partKey;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
