package pt.inesc.rectify.hibernate;
// Generated Apr 29, 2017 8:36:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * KbDbOp generated by hbm2java
 */
public class KbDbOp  implements java.io.Serializable {


     private Integer id;
     private KbHttpRequest kbHttpRequest;
     private Date ts;
     private String query;

    public KbDbOp() {
    }

	
    public KbDbOp(Date ts) {
        this.ts = ts;
    }
    public KbDbOp(KbHttpRequest kbHttpRequest, Date ts, String query) {
       this.kbHttpRequest = kbHttpRequest;
       this.ts = ts;
       this.query = query;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public KbHttpRequest getKbHttpRequest() {
        return this.kbHttpRequest;
    }
    
    public void setKbHttpRequest(KbHttpRequest kbHttpRequest) {
        this.kbHttpRequest = kbHttpRequest;
    }
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }
    public String getQuery() {
        return this.query;
    }
    
    public void setQuery(String query) {
        this.query = query;
    }




}


