package pt.inesc.rectify.hibernate;
// Generated May 2, 2017 6:29:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * KbDbStatement generated by hbm2java
 */
public class KbDbStatement  implements java.io.Serializable {


     private Integer id;
     private KbHttpRequest kbHttpRequest;
     private Date ts;
     private String query;
     private String statementType;
     private Integer nrOfColumns;
     private String columns;
     private String columnsValues;
     private String tables;
     private String whereClause;
     private String whereClauseValues;

    public KbDbStatement() {
    }

	
    public KbDbStatement(Date ts) {
        this.ts = ts;
    }
    public KbDbStatement(KbHttpRequest kbHttpRequest, Date ts, String query, String statementType, Integer nrOfColumns, String columns, String columnsValues, String tables, String whereClause, String whereClauseValues) {
       this.kbHttpRequest = kbHttpRequest;
       this.ts = ts;
       this.query = query;
       this.statementType = statementType;
       this.nrOfColumns = nrOfColumns;
       this.columns = columns;
       this.columnsValues = columnsValues;
       this.tables = tables;
       this.whereClause = whereClause;
       this.whereClauseValues = whereClauseValues;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public KbHttpRequest getKbHttpRequest() {
        return this.kbHttpRequest;
    }
    
    public void setKbHttpRequest(KbHttpRequest kbHttpRequest) {
        this.kbHttpRequest = kbHttpRequest;
    }
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }
    public String getQuery() {
        return this.query;
    }
    
    public void setQuery(String query) {
        this.query = query;
    }
    public String getStatementType() {
        return this.statementType;
    }
    
    public void setStatementType(String statementType) {
        this.statementType = statementType;
    }
    public Integer getNrOfColumns() {
        return this.nrOfColumns;
    }
    
    public void setNrOfColumns(Integer nrOfColumns) {
        this.nrOfColumns = nrOfColumns;
    }
    public String getColumns() {
        return this.columns;
    }
    
    public void setColumns(String columns) {
        this.columns = columns;
    }
    public String getColumnsValues() {
        return this.columnsValues;
    }
    
    public void setColumnsValues(String columnsValues) {
        this.columnsValues = columnsValues;
    }
    public String getTables() {
        return this.tables;
    }
    
    public void setTables(String tables) {
        this.tables = tables;
    }
    public String getWhereClause() {
        return this.whereClause;
    }
    
    public void setWhereClause(String whereClause) {
        this.whereClause = whereClause;
    }
    public String getWhereClauseValues() {
        return this.whereClauseValues;
    }
    
    public void setWhereClauseValues(String whereClauseValues) {
        this.whereClauseValues = whereClauseValues;
    }




}


