package pt.inesc.rectify.hibernate;
// Generated Nov 23, 2016 11:54:34 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * KbHttpResponse generated by hbm2java
 */
public class KbHttpResponse  implements java.io.Serializable {


     private Integer id;
     private KbHttpRequest kbHttpRequest;
     private Date ts;
     private Set kbHttpResponsePartses = new HashSet(0);

    public KbHttpResponse() {
    }

	
    public KbHttpResponse(KbHttpRequest kbHttpRequest, Date ts) {
        this.kbHttpRequest = kbHttpRequest;
        this.ts = ts;
    }
    public KbHttpResponse(KbHttpRequest kbHttpRequest, Date ts, Set kbHttpResponsePartses) {
       this.kbHttpRequest = kbHttpRequest;
       this.ts = ts;
       this.kbHttpResponsePartses = kbHttpResponsePartses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public KbHttpRequest getKbHttpRequest() {
        return this.kbHttpRequest;
    }
    
    public void setKbHttpRequest(KbHttpRequest kbHttpRequest) {
        this.kbHttpRequest = kbHttpRequest;
    }
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }
    public Set getKbHttpResponsePartses() {
        return this.kbHttpResponsePartses;
    }
    
    public void setKbHttpResponsePartses(Set kbHttpResponsePartses) {
        this.kbHttpResponsePartses = kbHttpResponsePartses;
    }




}


