package pt.inesc.rectify.hibernate;
// Generated Dec 3, 2016 4:44:04 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * KbHttpResponse generated by hbm2java
 */
public class KbHttpResponse implements java.io.Serializable {

	private Integer id;
	private KbHttpRequest kbHttpRequest;
	private Date ts;
	private Set<KbHttpResponseParts> kbHttpResponsePartses = new HashSet<KbHttpResponseParts>(0);

	public KbHttpResponse() {
	}

	public KbHttpResponse(KbHttpRequest kbHttpRequest, Date ts) {
		this.kbHttpRequest = kbHttpRequest;
		this.ts = ts;
	}

	public KbHttpResponse(KbHttpRequest kbHttpRequest, Date ts, Set<KbHttpResponseParts> kbHttpResponsePartses) {
		this.kbHttpRequest = kbHttpRequest;
		this.ts = ts;
		this.kbHttpResponsePartses = kbHttpResponsePartses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public KbHttpRequest getKbHttpRequest() {
		return this.kbHttpRequest;
	}

	public void setKbHttpRequest(KbHttpRequest kbHttpRequest) {
		this.kbHttpRequest = kbHttpRequest;
	}

	public Date getTs() {
		return this.ts;
	}

	public void setTs(Date ts) {
		this.ts = ts;
	}

	public Set<KbHttpResponseParts> getKbHttpResponsePartses() {
		return this.kbHttpResponsePartses;
	}

	public void setKbHttpResponsePartses(Set<KbHttpResponseParts> kbHttpResponsePartses) {
		this.kbHttpResponsePartses = kbHttpResponsePartses;
	}

}
