package pt.inesc.rectify.hibernate;
// Generated Nov 29, 2016 11:21:05 PM by Hibernate Tools 4.3.1



/**
 * KbHttpResponseParts generated by hbm2java
 */
public class KbHttpResponseParts  implements java.io.Serializable {


     private Integer id;
     private KbHttpResponse kbHttpResponse;
     private String type;
     private String partKey;
     private String value;

    public KbHttpResponseParts() {
    }

	
    public KbHttpResponseParts(KbHttpResponse kbHttpResponse) {
        this.kbHttpResponse = kbHttpResponse;
    }
    public KbHttpResponseParts(KbHttpResponse kbHttpResponse, String type, String partKey, String value) {
       this.kbHttpResponse = kbHttpResponse;
       this.type = type;
       this.partKey = partKey;
       this.value = value;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public KbHttpResponse getKbHttpResponse() {
        return this.kbHttpResponse;
    }
    
    public void setKbHttpResponse(KbHttpResponse kbHttpResponse) {
        this.kbHttpResponse = kbHttpResponse;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getPartKey() {
        return this.partKey;
    }
    
    public void setPartKey(String partKey) {
        this.partKey = partKey;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


