package pt.inesc.rectify.hibernate;
// Generated Nov 23, 2016 11:54:34 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LogDbResponse generated by hbm2java
 */
public class LogDbResponse  implements java.io.Serializable {


     private Integer id;
     private LogDbRequest logDbRequest;
     private Date ts;
     private String response;

    public LogDbResponse() {
    }

	
    public LogDbResponse(LogDbRequest logDbRequest, Date ts) {
        this.logDbRequest = logDbRequest;
        this.ts = ts;
    }
    public LogDbResponse(LogDbRequest logDbRequest, Date ts, String response) {
       this.logDbRequest = logDbRequest;
       this.ts = ts;
       this.response = response;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public LogDbRequest getLogDbRequest() {
        return this.logDbRequest;
    }
    
    public void setLogDbRequest(LogDbRequest logDbRequest) {
        this.logDbRequest = logDbRequest;
    }
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }
    public String getResponse() {
        return this.response;
    }
    
    public void setResponse(String response) {
        this.response = response;
    }




}


