package pt.inesc.rectify.hibernate;
// Generated Dec 3, 2016 4:22:13 PM by Hibernate Tools 5.2.0.Beta1

/**
 * LogDbSubOperation generated by hbm2java
 */
public class LogDbSubOperation implements java.io.Serializable {

	private Integer id;
	private LogDbOperation logDbOperation;
	private Integer pk;

	public LogDbSubOperation() {
	}

	public LogDbSubOperation(LogDbOperation logDbOperation, Integer pk) {
		this.logDbOperation = logDbOperation;
		this.pk = pk;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public LogDbOperation getLogDbOperation() {
		return this.logDbOperation;
	}

	public void setLogDbOperation(LogDbOperation logDbOperation) {
		this.logDbOperation = logDbOperation;
	}

	public Integer getPk() {
		return this.pk;
	}

	public void setPk(Integer pk) {
		this.pk = pk;
	}

}
