package pt.inesc.rectify.hibernate;
// Generated Nov 29, 2016 11:21:05 PM by Hibernate Tools 4.3.1



/**
 * LogDbSubOperation generated by hbm2java
 */
public class LogDbSubOperation  implements java.io.Serializable {


     private Integer id;
     private LogDbOperation logDbOperation;
     private Integer pk;

    public LogDbSubOperation() {
    }

    public LogDbSubOperation(LogDbOperation logDbOperation, Integer pk) {
       this.logDbOperation = logDbOperation;
       this.pk = pk;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public LogDbOperation getLogDbOperation() {
        return this.logDbOperation;
    }
    
    public void setLogDbOperation(LogDbOperation logDbOperation) {
        this.logDbOperation = logDbOperation;
    }
    public Integer getPk() {
        return this.pk;
    }
    
    public void setPk(Integer pk) {
        this.pk = pk;
    }




}


