package pt.inesc.rectify.hibernate;
// Generated May 1, 2017 3:05:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LogHttpRequest generated by hbm2java
 */
public class LogHttpRequest  implements java.io.Serializable {


     private Integer id;
     private Date ts;
     private String request;
     private String uri;
     private String host;
     private Set logHttpResponses = new HashSet(0);

    public LogHttpRequest() {
    }

	
    public LogHttpRequest(Date ts) {
        this.ts = ts;
    }
    public LogHttpRequest(Date ts, String request, String uri, String host, Set logHttpResponses) {
       this.ts = ts;
       this.request = request;
       this.uri = uri;
       this.host = host;
       this.logHttpResponses = logHttpResponses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }
    public String getRequest() {
        return this.request;
    }
    
    public void setRequest(String request) {
        this.request = request;
    }
    public String getUri() {
        return this.uri;
    }
    
    public void setUri(String uri) {
        this.uri = uri;
    }
    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }
    public Set getLogHttpResponses() {
        return this.logHttpResponses;
    }
    
    public void setLogHttpResponses(Set logHttpResponses) {
        this.logHttpResponses = logHttpResponses;
    }




}


