package pt.inesc.rectify.hibernate;
// Generated Dec 3, 2016 4:22:13 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LogHttpRequest generated by hbm2java
 */
public class LogHttpRequest implements java.io.Serializable {

	private Integer id;
	private Date ts;
	private String request;
	private String uri;
	private Set<LogHttpResponse> logHttpResponses = new HashSet<LogHttpResponse>(0);

	public LogHttpRequest() {
	}

	public LogHttpRequest(Date ts) {
		this.ts = ts;
	}

	public LogHttpRequest(Date ts, String request, String uri, Set<LogHttpResponse> logHttpResponses) {
		this.ts = ts;
		this.request = request;
		this.uri = uri;
		this.logHttpResponses = logHttpResponses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getTs() {
		return this.ts;
	}

	public void setTs(Date ts) {
		this.ts = ts;
	}

	public String getRequest() {
		return this.request;
	}

	public void setRequest(String request) {
		this.request = request;
	}

	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	public Set<LogHttpResponse> getLogHttpResponses() {
		return this.logHttpResponses;
	}

	public void setLogHttpResponses(Set<LogHttpResponse> logHttpResponses) {
		this.logHttpResponses = logHttpResponses;
	}

}
