package pt.inesc.rectify.hibernate;
// Generated Dec 1, 2016 10:02:07 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * RectifyLog generated by hbm2java
 */
public class RectifyLog implements java.io.Serializable {

	private Integer id;
	private String level;
	private String message;
	private Date ts;
	private String title;

	public RectifyLog() {
	}

	public RectifyLog(Date ts) {
		this.ts = ts;
	}

	public RectifyLog(String level, String message, Date ts, String title) {
		this.level = level;
		this.message = message;
		this.ts = ts;
		this.title = title;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Date getTs() {
		return this.ts;
	}

	public void setTs(Date ts) {
		this.ts = ts;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
