package pt.inesc.rectify.hibernate;
// Generated Apr 29, 2017 8:36:51 PM by Hibernate Tools 4.3.1



/**
 * TrainningRoute generated by hbm2java
 */
public class TrainningRoute  implements java.io.Serializable {


     private Integer id;
     private String route;

    public TrainningRoute() {
    }

    public TrainningRoute(String route) {
       this.route = route;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRoute() {
        return this.route;
    }
    
    public void setRoute(String route) {
        this.route = route;
    }




}


